### ISSUE TITLE
name contains an apostrophe

### ISSUE THREAD

**Issue by demosat** [E2OpenPlugins/e2openplugin-OpenWebif#1510]
Hi,
It is not possible to zap on a channel when click on the name of the chain when it contains an apostrophe. 

Example with French channels :
L'Equipe (5w, 13e, 19.2e)
TOUTE L'HISTOIRE (5w and 13e)

**Comment by wedebe** [comment]
Ooh, thought we'd fixed this ages ago. Are you uusing the modern or classic interface?

**Comment by demosat** [comment]
this is screen shoot.
![Screenshot 2022-05-30 at 18-49-32 Edision OS Mio 4K - OpenWebif](https://user-images.githubusercontent.com/15945175/171034674-bbd33bfb-7388-4018-873d-ce64ce9adc18.png)

**Comment by demosat** [comment]
All interfaces are affected by the problem.

**Comment by wedebe** [comment]
I've found an issue with the event detail modal in the modern interface.

**Comment by demosat** [comment]
> @demosat, have you seen this happen elsewhere in the modern interface?

Yes, All interfaces are affected by the problem.

**Comment by wedebe** [comment]
> > @demosat, have you seen this happen elsewhere in the modern interface?
> 
> Yes, All interfaces are affected by the problem.

Could you be more specific about exactly where (within each interface) the issue happens when you zap, please? 
The now/next list was fixed some time ago, I've just now submitted a fix for the programme details popup.

**Comment by demosat** [comment]
All skins have problem.
It is not possible to zap on a channel when click on the name of the chain when it contains an apostrophe.
If you have possibility, test on channel orbital 5w or 13e or 19.2e with "L'equipe" or "Toute l'histoire"
But i waiting your fix on update opkg

**Comment by t5k6** [comment]
I've tried on both modern and classic interfaces and I can zap to "L'equipe" just fine 🤔.
(OWIF 1.5.1 / Build: 1.5.0-git4413+16a8d01-r0)

**Comment by demosat** [comment]
I use latest openpli 8.2
root@osmio4kplus:~# opkg list | grep openwebif
enigma2-plugin-extensions-openwebif - 1+git4396+f551074-r0.1 - enigma2-plugin-extensions-openwebif version 1+gitAUTOINC+f5510743e1-r0

**Comment by demosat** [comment]
I remove openwebif -> reboot > install enigma2-plugin-extensions-openwebif_latest_all.ipk 
18:30 paris local time (https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/raw/gh-pages/enigma2-plugin-extensions-openwebif_latest_all.ipk) 
I test on Firefox or Chrome, but problem isn't solved.

**Comment by wedebe** [comment]
@demosat, please take a screenshot and mark everywhere you experience this problem.

**Comment by demosat** [comment]
Hi, i make video for this problem. look my video please,
i deposit on megaupload.
[https://mega.nz/file/WzBVSJiS#txA7IRNHffBDSWvBw-Eg8fWpTIXT1WaxunWoG8Tqpi0](url)

**Comment by demosat** [comment]
Have you understood the problem with my video following the action of the cursor on the computer ?

**Comment by demosat** [comment]
Compare
good link
<a href="#" onclick="zapChannel("1:0:19:2332:442:1:C00000:0:0:0:", "INFOSPORT+"); return false" title="Zapper vers INFOSPORT+">INFOSPORT+</a>

bad link
<a href="#" onclick="zapChannel("1:0:19:2076:432:1:C00000:0:0:0:", "L" equipe");="" return="" false'="" title="Zapper vers L'EQUIPE">L'EQUIPE</a>

![Sans-titre-1](https://user-images.githubusercontent.com/15945175/174847565-8fbac086-119c-4cd2-a02c-9fd42069a7f5.jpg)

**Comment by demosat** [comment]
@Jblleyel, i dont touch or modification code, i just post screenshoot on console
I compar good link for normal name vs bad link name wtih apostrophe

**Comment by wedebe** [comment]
I really want to rewrite the zap function completely but don't have the time at the moment.
